package pravila;

global Integer najveciBrojSvidjanja;

rule "Ucesce je 0"
salience 15
agenda-group "preporuka"
    when
    	$k: UcesceKorisnika($knjige: korisnik.lajkovaneKnjige.size() < 0.1 * najveciBrojSvidjanja)
    then
        System.out.println("*** Korisnik " + $k.getKorisnik().getKorisnickoIme() + " ima broj svidjanja " + $knjige + " ucesce 0");
        modify($k) { setUcesce(0.0); }
end

rule "Ucesce je 0.25"
salience 15
agenda-group "preporuka"
    when
    	$k: UcesceKorisnika($kIme: korisnik.korisnickoIme, 
    		$knjige: korisnik.lajkovaneKnjige.size() >= 0.1 * najveciBrojSvidjanja && $knjige < 0.3 * najveciBrojSvidjanja)
    then
        System.out.println("*** Korisnik " + $k.getKorisnik().getKorisnickoIme() + " ima broj svidjanja " + $knjige + " ucesce 0.25");
        modify($k) { setUcesce(0.25); }
end

rule "Ucesce je 0.5"
salience 15
agenda-group "preporuka"
    when
    	$k: UcesceKorisnika($kIme: korisnik.korisnickoIme, 
    		$knjige: korisnik.lajkovaneKnjige.size() >= 0.3 * najveciBrojSvidjanja && $knjige < 0.5 * najveciBrojSvidjanja)
    then
        System.out.println("*** Korisnik " + $k.getKorisnik().getKorisnickoIme() + " ima broj svidjanja " + $knjige + " ucesce 0.5");
        modify($k) { setUcesce(0.5); }
end

rule "Ucesce je 0.75"
salience 15
agenda-group "preporuka"
    when
    	$k: UcesceKorisnika($kIme: korisnik.korisnickoIme, 
    		$knjige: korisnik.lajkovaneKnjige.size() >= 0.5 * najveciBrojSvidjanja && $knjige < 0.7 * najveciBrojSvidjanja)
    then
        System.out.println("*** Korisnik " + $k.getKorisnik().getKorisnickoIme() + " ima broj svidjanja " + $knjige + " ucesce 0.75");
        modify($k) { setUcesce(0.75); }
end

rule "Ucesce je 1"
salience 15
agenda-group "preporuka"
    when
    	$k: UcesceKorisnika($kIme: korisnik.korisnickoIme, $knjige: korisnik.lajkovaneKnjige.size() >= 0.7 * najveciBrojSvidjanja)
    then
        System.out.println("*** Korisnik " + $k.getKorisnik().getKorisnickoIme() + " ima broj svidjanja " + $knjige + " ucesce 1");
        modify($k) { setUcesce(1.0); }
end