package pravila;

import upravljanje.Korisnik;
import upravljanje.Knjiga;

global Knjiga posmatranaKnjiga;

declare UcesceKorisnika
	korisnik: Korisnik
	ucesce: Double
end

rule "Filter korisnika kojima se svidja posmatrana knjiga"
salience 16
agenda-group "preporuka"
    when
    	$k: Korisnik($knjige: lajkovaneKnjige) Number(intValue == 1) from
     		accumulate (Knjiga (isbn == posmatranaKnjiga.isbn) from $knjige, count(1))
    then
        System.out.println("*** Kome se svidja posmatrana knjiga " + $k.getKorisnickoIme());
        UcesceKorisnika zaDodavanje = new UcesceKorisnika();
        zaDodavanje.setKorisnik($k);
        insert(zaDodavanje);
end
