package pravila;

import model.Knjiga;

declare OcenjenaKnjiga
	knjiga: Knjiga
	ocena: Double
end

rule "Ocenjivanje knjiga zavisno od korisnika"
salience 10
agenda-group "preporuka"
    when
    	$k: UcesceKorisnika($knjige: korisnik.lajkovaneKnjige, $udeo: ucesce)
    	$knjiga: Knjiga() from $knjige
    then
        System.out.println("*** Korisnik " + $k.getKorisnik().getKorisnickoIme() + " daje udeo " + $udeo + " za knjigu " + $knjiga.getNaziv());
        
        OcenjenaKnjiga zaDodavanje = new OcenjenaKnjiga();
        zaDodavanje.setKnjiga($knjiga);
        zaDodavanje.setOcena($udeo);
        insert(zaDodavanje);
end