package pravila;

import model.Korisnik;
import model.Knjiga;
import java.util.List;
import java.util.Collections;

global Knjiga posmatranaKnjiga;
global List<Korisnik> korisnici;

rule "Filter korisnika kojima se svidja posmatrana knjiga"
salience 16
agenda-group "preporuka"
    when
    	$k: Korisnik($knjige: lajkovaneKnjige) Number(intValue == 1) from
     		accumulate (Knjiga (ISBN == posmatranaKnjiga.ISBN) from $knjige, count(1))
    then
        System.out.println("*** Kome se svidja posmatrana knjiga " + $k);
        korisnici.add($k);
        //drools.getKnowledgeRuntime().setGlobal("korisnici", korisnici);
        //drools.getKnowledgeRuntime().getAgenda().getActivationGroup("Racunanje ucesca").clear();
end