package pravila;

import model.Korisnik;
import java.util.List;
import java.util.Map;

global List<Korisnik> korisnici;
global Map<String, Double> ucesca;
global Integer najveciBrojSvidjanja;

rule "Ucesce je 0"
salience 15
agenda-group "preporuka"
    when
    	$k: Korisnik($kIme: korisnickoIme, $knjige: lajkovaneKnjige.size() < 0.1 * najveciBrojSvidjanja) from korisnici
    then
        System.out.println("*** Korisnik " + $kIme + "ima broj svidjanja " + $knjige + " ucesce 0");
        ucesca.put($kIme, 0.0);
end

rule "Ucesce je 0.25"
salience 15
agenda-group "preporuka"
    when
    	$k: Korisnik($kIme: korisnickoIme, $knjige: lajkovaneKnjige.size() >= 0.1 * najveciBrojSvidjanja &&  
    		$knjige < 0.3 * najveciBrojSvidjanja) from korisnici
    then
        System.out.println("*** Korisnik " + $kIme + "ima broj svidjanja " + $knjige + " ucesce 0.25");
        ucesca.put($kIme, 0.25);
end

rule "Ucesce je 0.5"
salience 15
agenda-group "preporuka"
    when
    	$k: Korisnik($kIme: korisnickoIme, $knjige: lajkovaneKnjige.size() >= 0.3 * najveciBrojSvidjanja && 
    		$knjige < 0.5 * najveciBrojSvidjanja) from korisnici
    then
        System.out.println("*** Korisnik " + $kIme + "ima broj svidjanja " + $knjige + " ucesce 0.5");
        ucesca.put($kIme, 0.5);
end

rule "Ucesce je 0.75"
salience 15
agenda-group "preporuka"
    when
    	$k: Korisnik($kIme: korisnickoIme, $knjige: lajkovaneKnjige.size() >= 0.5 * najveciBrojSvidjanja && 
    		$knjige < 0.7 * najveciBrojSvidjanja) from korisnici
    then
        System.out.println("*** Korisnik " + $kIme + "ima broj svidjanja " + $knjige + " ucesce 0.75");
        ucesca.put($kIme, 0.75);
end

rule "Ucesce je 1"
salience 15
agenda-group "preporuka"
    when
    	$k: Korisnik($kIme: korisnickoIme, $knjige: lajkovaneKnjige.size() >= 0.7 * najveciBrojSvidjanja) from korisnici
    then
        System.out.println("*** Korisnik " + $kIme + "ima broj svidjanja " + $knjige + " ucesce 1");
        ucesca.put($kIme, 1.0);
end