package pravila;

import model.Korisnik;
import model.Knjiga;
import java.util.ArrayList;
import java.util.Map;

global ArrayList korisnici;
global Map<String, Double> ucesca;
global Map<Knjiga, Double> ocenjeneKnjige;

rule "Proba jos jedna"
salience 3
    when
        $korisnik: Korisnik ()
 		$x : Object() from accumulate($k: Knjiga(); collectList( $k ) )
    then
        System.out.println("Proba uspelaaa");
        System.out.println("objekat   " + $korisnik);
        System.out.println("kolekcija   " + $x);
        System.out.println("korisnici   " + korisnici);
        System.out.println("ucesca   " + ucesca);
        System.out.println("ocenjeneKnjige   " + ocenjeneKnjige);
        System.out.println("---------------");
end