package pravila;

import model.Knjiga;
import java.util.HashSet;

declare KonacnaOcena
	knjiga: Knjiga
	ocena: Double
end

rule "Sabiranje glasova za svaku knjigu"
salience 9
agenda-group "preporuka"
    when
    	$lista: List() from accumulate (OcenjenaKnjiga($knjiga: knjiga); collectList( $knjiga ))
    	$k: Knjiga() from new HashSet($lista)
    	
    	accumulate (OcenjenaKnjiga(knjiga == $k, $glas: ocena), $suma: sum($glas))
    then
        System.out.println("*** Knjiga " + $k.getNaziv() + " suma glasova " + $suma);
        
        KonacnaOcena zaDodavanje = new KonacnaOcena();
        zaDodavanje.setKnjiga($k);
        zaDodavanje.setOcena(1.0);
        insert(zaDodavanje);
end